apiVersion: v1
kind: Service
metadata:
  name: linkhub
  namespace: linkhub
  labels:
    app: linkhub
spec:
  type: ClusterIP
  selector:
    app: linkhub
  ports:
    - name: http
      port: 80
      targetPort: http
